[project]
name = "hello-mcp-a2a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[http-server]>=0.3.1",
    "mcp>=1.13.0",
    "openai-agents>=0.2.7",
]
